config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  get 'about' => 'abouts#about'

#初期のdeviseの設定だとadminとuserで見分けがつけにくい為下記記述でわかりやすくする
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}





  namespace :admins do
  	resources :users, only:[:index, :show, :edit, :update]
  	resources :construction_sites, only:[:index, :new, :create, :show, :edit, :update]
  	resources :photos, only:[:index, :show]
  	resources :attendance_records, only:[:index, :show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :machines, only:[:index, :create, :update]
    resources :reservations, only:[:index, :new, :create, :show, :destroy]
    resources :cars, only:[:index, :create, :edit, :update]
  	root 'homes#top'
  end




  namespace :users do
  	resources :attendance_records, only:[:index, :create, :show, :edit, :update] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:create, :show, :edit, :update, :destroy] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :users, only:[:show, :edit, :update]
  	resources :construction_sites, only:[:index, :show, :edit, :update] do
      member do
        get :map, as: :map
      end
    end
  	resources :photos, only:[:new, :create, :show, :destroy]
  	resources :machines, only:[:index, :update]
    resources :reservations, only:[:index, :new, :create, :show]
  	root 'homes#top'
  end

  namespace :users do
    get 'uploader/index'
    get 'uploader/download'
  end
  namespace :admins do
    get 'uploader/index'
    post 'uploader/upload'
    get 'uploader/download'
  end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance_record.rb
class AttendanceRecord < ApplicationRecord

	belongs_to :user
	belongs_to :construction_site

	validates :construction_site, presence: true


end

app/models/car.rb
class Car < ApplicationRecord

	has_many :reservations

	validates :name, presence: true

end

app/models/construction_site.rb
class ConstructionSite < ApplicationRecord

	has_many :attendance_records
	has_many :daily_reports
	has_many :machines
  has_many :reservations
  has_many :upload_files
	has_many :photos, dependent: :destroy
  accepts_attachments_for :photos, attachment: :image

  validates :name, presence: true
  validates :address, presence: true
  validates :prime_contractor, presence: true
  validates :foremen, presence: true
  validates :period, presence: true
  validates :period_end, presence: true
  validates :caution, presence: true

	enum process:{
    着工前: 0,
    着工中: 1,
    完工: 2,
    その他: 3,
  }

  def self.search(search)
      if search
        ConstructionSite.where(['name LIKE ? OR address LIKE ? OR prime_contractor LIKE ? OR foremen LIKE ?',
         "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
      else
        ConstructionSite.all
      end
  end


end

app/models/daily_report.rb
class DailyReport < ApplicationRecord

	belongs_to :construction_site

	validates :construction_site, presence: true
	validates :content, presence: true
	validates :company_people, presence: true

end

app/models/machine.rb
class Machine < ApplicationRecord

	belongs_to :construction_site

	validates :name, presence: true

	def self.search(search)
      if search
        Machine.where(['name LIKE ? OR construction_site_id LIKE ?',
         "%#{search}%", "%#{search}%"])
      else
        Machine.all
      end
  end

end

app/models/photo.rb
class Photo < ApplicationRecord

	belongs_to :construction_site

	attachment :image, destroy: false

end

app/models/reservation.rb
class Reservation < ApplicationRecord

	belongs_to :car
	belongs_to :construction_site

	validates :content, presence: true

end

app/models/upload_file.rb
class UploadFile < ApplicationRecord
	mount_uploader :file, UploadFileUploader
	belongs_to :construction_site
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :attendance_records


	validates :family_name, presence: true
  	validates :first_name, presence: true
  	validates :family_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/ }, length: { maximum: 20 }
  	validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}, length: { maximum: 20 }
  	validates :address, presence: true
  	validates :telephone_number, presence: true, numericality: { only_integer: true }
  	validates :email, presence: true

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

	def about
	end

end

app/controllers/admins/reservations_controller.rb
class Admins::ReservationsController < ApplicationController
 before_action :authenticate_admin!

	def index
		@reservations = Reservation.all
	end

	def new
		@reservation = Reservation.new
	end

	def create
		@reservation = Reservation.new(reservation_params)
		if @reservation.save
		 flash[:notice] = "配車予約が完了しました！"
		 redirect_to admins_reservations_path
		else
		 render action: :new
		end
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.destroy
		flash[:notice] = "配車予約を削除しました！"
		redirect_to admins_reservations_path
	end

	private
  		def reservation_params
    		params.require(:reservation).permit(
    			:car_id,
   				:construction_site_id,
   				:content,
   				:start_time,
   				:finish_at)
  		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
		case resource
		when Admin
	    	admins_root_path
	  	when User
	    	users_root_path
	  	end
	end

	def after_sign_up_path_for(resource)
		admins_users_path
	end

	# def after_sign_out_path_for(resource)
	# 	case resource
	# 	when Admin
	# 		new_admin_session_path
	# 	when User
	# 		new_user_session_path
	# 	end
	# end


	# deviseに関わる全てのアクションの前にconfigure_permitted_parametersをさせる
	# つまりキーをコントローラに受け取らせる
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:family_name, :first_name , :family_name_kana, :first_name_kana, :postal_code, :address,:telephone_number])
	end

end

app/controllers/users/reservations_controller.rb
class Users::ReservationsController < ApplicationController
 before_action :authenticate_user!

	def index
		@reservations = Reservation.all
	end

	def new
		@reservation = Reservation.new
	end

	def create
		@reservation = Reservation.new(reservation_params)
		if @reservation.save
			flash[:notice] = "配車予約が完了しました！"
			redirect_to users_reservations_path
		else
			render action: :new
		end
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	private
  		def reservation_params
    		params.require(:reservation).permit(
    			:car_id,
   				:construction_site_id,
   				:content,
   				:start_time,
   				:finish_at)
  		end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins/cars_helper.rb
module Admins::CarsHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/reservations_helper.rb
module Admins::ReservationsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/reservations_helper.rb
module Users::ReservationsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/reservations/index.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

	<div class = "row">

		<div class="title">配車予約カレンダー</div>
		<div class="btn1"><%= link_to "配車予約", new_admins_reservation_path, class: "btn btn-danger" %></div>

	</div>


	<div class= "row">


		<%= month_calendar events: @reservations do |date, reservations| %>
			<%= date.day %>

			<% reservations.each do |reservation| %>
				<div>
					<%= link_to admins_reservation_path(reservation.id) do %>
					<%= reservation.car.name %><br>
					<%= reservation.start_time.strftime("%H:%M") %>〜<%= reservation.finish_at.strftime("%H:%M") %>
					<% end %>
				</div>
			<% end %>

		<% end %>

	</div>

</div>

app/views/admins/reservations/new.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

  <% if @reservation.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(@reservation.errors.count, "error") %></h4>
      <p><%= pluralize(@reservation.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
      <hr>
        <p class="mb-0">
        <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </p>
    </div>
  <% end %>

  <div class = "row">

  	<div class="col-xs-7">

  		<div class="title">配車 予約</div>

  		<%= form_for @reservation, url: admins_reservations_path, method: :post do |f| %>


      <table class="table" id="none-border">

          <tbody>

            <tr>
              <td><%= f.label :construction_site, "現場名" %></td>
              <td><%= f.collection_select(:construction_site_id, ConstructionSite.all, :id, :name,:prompt => "選択してください") %></td>
            </tr>

            <tr>
              <td><%= f.label :car, "車種選択" %></td>
              <td><%= f.collection_select(:car_id, Car.where(still_run: true), :id, :name,:prompt => "選択してください") %></td>
            </tr>

            <tr>
              <td><%= f.label :時間 %></td>
              <td><%= f.datetime_select :start_time, {default: Date.today + 8.hour}, minute_step: 30 %>
                  <%= "〜" %>
                  <%= f.datetime_select :finish_at, {default: Date.today + 17.hour}, minute_step: 30 %></td>
            </tr>

            <tr>
              <td><%= f.label :作業内容 %></td>
              <td><%= f.text_field :content %></td>
            </tr>

          </tbody>

      </table>

  		<div class = "btn1"><%= f.submit "予約", class: "btn btn-primary" %></div>

  		<% end %>

  	</div>

  </div>

</div>

app/views/admins/reservations/show.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

	<div class= "row">

  		<div class="col-xs-4">

        <div class="title">配車予約 詳細</div>

          <table class="table">
            <tbody>
              <tr>
         	      <th>現場名</th>
                <td><%= @reservation.construction_site.name %></td>
       	      </tr>

       	      <tr>
       	        <th>車種</th>
                <td><%= @reservation.car.name %></td>
       	      </tr>

       	      <tr>
                <th>時間</th>
                <td><%= @reservation.start_time.strftime("%Y-%m-%d %H:%M") %> 〜 <%= @reservation.finish_at.strftime("%Y-%m-%d %H:%M") %></td>
       	      </tr>

              <tr>
                <th>作業内容</th>
                <td><%= @reservation.content %></td>
              </tr>

            </tbody>
          </table>

          <div class="btn1"><%= link_to "予約を削除する", admins_reservation_path(@reservation), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger" %></div>

      </div>

  </div>

</div>