config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  get 'about' => 'abouts#about'

#初期のdeviseの設定だとadminとuserで見分けがつけにくい為下記記述でわかりやすくする
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}





  namespace :admins do
  	resources :users, only:[:index, :show, :edit, :update]
  	resources :construction_sites, only:[:index, :new, :create, :show, :edit, :update]
  	resources :photos, only:[:index, :show]
  	resources :attendance_records, only:[:index, :show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :machines, only:[:index, :create, :update]
    resources :reservations, only:[:index, :new, :create, :show, :destroy]
    resources :cars, only:[:index, :create, :edit, :update]
  	root 'homes#top'
  end




  namespace :users do
  	resources :attendance_records, only:[:index, :create, :show, :edit, :update] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:create, :show, :edit, :update, :destroy] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :users, only:[:show, :edit, :update]
  	resources :construction_sites, only:[:index, :show, :edit, :update] do
      member do
        get :map, as: :map
      end
    end
  	resources :photos, only:[:new, :create, :show, :destroy]
  	resources :machines, only:[:index, :update]
    resources :reservations, only:[:index, :new, :create, :show]
  	root 'homes#top'
  end

  namespace :users do
    get 'uploader/index'
    get 'uploader/download'
  end
  namespace :admins do
    get 'uploader/index'
    post 'uploader/upload'
    get 'uploader/download'
  end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/construction_site.rb
class ConstructionSite < ApplicationRecord

	has_many :attendance_records
	has_many :daily_reports
	has_many :machines
  has_many :reservations
  has_many :upload_files
	has_many :photos, dependent: :destroy
  accepts_attachments_for :photos, attachment: :image

  validates :name, presence: true
  validates :address, presence: true
  validates :prime_contractor, presence: true
  validates :foremen, presence: true
  validates :period, presence: true
  validates :period_end, presence: true
  validates :caution, presence: true

	enum process:{
    着工前: 0,
    着工中: 1,
    完工: 2,
    その他: 3,
  }

  def self.search(search)
      if search
        ConstructionSite.where(['name LIKE ? OR address LIKE ? OR prime_contractor LIKE ? OR foremen LIKE ?',
         "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
      else
        ConstructionSite.all
      end
  end


end

app/controllers/admins/construction_sites_controller.rb
class Admins::ConstructionSitesController < ApplicationController
 before_action :authenticate_admin!
 GET_LIMIT = 10

	def index
		@construction_sites = ConstructionSite.page(params[:page]).per(GET_LIMIT).search(params[:search]).order(created_at: :desc)
	end

	def new
		@construction_site = ConstructionSite.new
	end

	def create
		@construction_site = ConstructionSite.new(construction_site_params)
		if @construction_site.save
			flash[:notice] = "新しい現場を追加しました！"
			redirect_to admins_construction_site_path(@construction_site.id)
		else
			render action: :new
		end
	end

	def show
		@construction_site = ConstructionSite.find(params[:id])
		@photos = @construction_site.photos.page(params[:page]).per(6).order(created_at: :desc)
	end

	def edit
		@construction_site = ConstructionSite.find(params[:id])
	end

	def update
		@construction_site = ConstructionSite.find(params[:id])
    	if @construction_site.update(construction_site_params)
    		flash[:notice] = "現場情報を編集しました！"
      		redirect_to admins_construction_site_path(@construction_site.id)
    	else
      		render action: :edit
    	end
	end

	private
	def construction_site_params
		params.require(:construction_site).permit(
			:name, :address, :prime_contractor, :foremen, :process, :period, :period_end, :caution)
	end

end

app/controllers/users/construction_sites_controller.rb
class Users::ConstructionSitesController < ApplicationController
 before_action :authenticate_user!
 GET_LIMIT = 10

	def index
		@construction_sites = ConstructionSite.page(params[:page]).per(GET_LIMIT).search(params[:search]).order(created_at: :desc)
	end

	def show
		@construction_site = ConstructionSite.find(params[:id])
		@photos = @construction_site.photos.page(params[:page]).per(6).order(created_at: :desc)
	end

	def map
		@construction_site = ConstructionSite.find(params[:id])
	end

	def edit
		@construction_site = ConstructionSite.find(params[:id])
	end

	def update
		@construction_site = ConstructionSite.find(params[:id])
    	if @construction_site.update(construction_site_params)
    		flash[:notice] = "現場情報を編集しました！"
      		redirect_to users_construction_site_path(@construction_site.id)
    	else
      		render action: :edit
    	end
	end

	private
	def construction_site_params
		params.require(:construction_site).permit(
			:name, :address, :prime_contractor, :foremen, :process, :period, :period_end, :caution)
	end


end

app/helpers/admins/construction_sites_helper.rb
module Admins::ConstructionSitesHelper
end

app/helpers/users/construction_sites_helper.rb
module Users::ConstructionSitesHelper
end

app/views/admins/construction_sites/edit.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

  <% if @construction_site.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(@construction_site.errors.count, "error") %></h4>
      <p><%= pluralize(@construction_site.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
      <hr>
        <p class="mb-0">
        <% @construction_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </p>
    </div>
  <% end %>

  <div class = "row">

  <div class="col-xs-7">

    <div class="title">現場 情報編集</div>

  <%= form_for @construction_site, url: admins_construction_site_path(@construction_site.id) do |f| %>

  <table class="table">

    <tbody>

      <tr>
        <td><%= f.label :現場名 %></td>
        <td><%= f.text_field :name, :size => "43*30" %></td>
      </tr>

      <tr>
        <td><%= f.label :現場住所 %></td>
        <td><%= f.text_field :address, :size => "43*30" %></td>
      </tr>

       <tr>
        <td><%= f.label :元請け業者 %></td>
        <td><%= f.text_field :prime_contractor %></td>
      </tr>

      <tr>
        <td><%= f.label :現場職長 %></td>
        <td><%= f.text_field :foremen %></td>
      </tr>

      <tr>
        <td><%= f.label :現在の工程 %></td>
        <td><%= f.select :process, ConstructionSite.processes.keys.to_a %></td>
      </tr>

      <tr>
        <td><%= f.label :工期 %></td>
        <td><%= raw sprintf(f.date_select(:period,prefix:'birthday', start_year: Time.now.year,end_year: (Time.now.year + 10),default: Date.new, date_separator:'%s'),'年','月')+'日' %>&emsp;〜<br><%= raw sprintf(f.date_select(:period_end, start_year: Time.now.year,end_year: (Time.now.year + 10),default: Date.new, date_separator:'%s'),'年','月')+'日' %></td>
      </tr>

      <tr>
        <td><%= f.label :その他（注意事項） %></td>
        <td><%= f.text_field :caution %></td>
      </tr>

    </tbody>

  </table>

  <div class="btn1"><%= f.submit "変更を保存", class: "btn btn-primary" %></div>

  <% end %>

</div>

</div>

</div>

app/views/admins/construction_sites/index.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

	<div class= "row">

  		<div class="col-xs-12">

    		<div class="title">現場一覧&ensp;
	 				<%= link_to new_admins_construction_site_path, :style=>"color:black;" do %>
	 					<i class="fas fa-plus"></i>
	 				<% end %>
			</div>

			<div class="searsh">
				<%= form_tag(admins_construction_sites_path,:method => 'get') do %>
				<label>絞り込み検索</label>
  				<%= text_field_tag :search, params[:search] %>
  				<%= submit_tag '検索', :name => nil %>
  				<% end %>
			</div>


		<table class="table table-hover">

	    	<thead class = "thead-light">
	    		<tr class="active">
		    		<th>現場名</th>
		    		<th>現場住所</th>
		    		<th>元請</th>
		    		<th>職長</th>
		    		<th>現在の工程</th>
		    		<th></th>
		    		<th></th>
		  		</tr>
	    	</thead>

	  		<% @construction_sites.each do |construction_site| %>
	    	<tbody>
				<tr>
					<td><%= construction_site.name %></td>
					<td><%= construction_site.address %></td>
					<td><% if construction_site.prime_contractor != "弊社" %>
						<%= construction_site.prime_contractor + "様" %>
						<% else %>
						<%= construction_site.prime_contractor %>
						<% end %>
					</td>
					<td><%= construction_site.foremen %></td>
					<td><%= construction_site.process %></td>
					<td><%= link_to "詳細",admins_construction_site_path(construction_site.id), class: 'btn btn-primary' %></td>
					<td><%= link_to "現場日報",calendar_admins_daily_report_path(construction_site.id), class: 'btn btn-primary' %></td>
				</tr>
			</tbody>
			<% end %>
		</table>

		</div>

		<div class = "paginate"><%= paginate @construction_sites %></div>

	</div>

</div>

app/views/admins/construction_sites/new.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

  <% if @construction_site.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(@construction_site.errors.count, "error") %></h4>
      <p><%= pluralize(@construction_site.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
      <hr>
        <p class="mb-0">
        <% @construction_site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </p>
    </div>
  <% end %>

  <div class = "row">

  <div class="col-xs-7">

  <div class="title">現場 新規登録</div>

  <%= form_for @construction_site, url: admins_construction_sites_path(current_admin.id) do |f| %>

  <table class="table" id="none-border">

    <tbody>

      <tr>
        <td><%= f.label :現場名 %></td>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <td><%= f.label :現場住所 %></td>
        <td><%= f.text_field :address %></td>
      </tr>

       <tr>
        <td><%= f.label :元請け業者 %></td>
        <td><%= f.text_field :prime_contractor %></td>
      </tr>

      <tr>
        <td><%= f.label :現場職長 %></td>
        <td><%= f.text_field :foremen %></td>
      </tr>

      <tr>
        <td><%= f.label :工期 %></td>
        <td><%= raw sprintf(f.date_select(:period, start_year: Time.now.year,end_year: (Time.now.year + 10),default: Date.new, date_separator:'%s'),'年','月')+'日' %>&emsp;から<br><%= raw sprintf(f.date_select(:period_end, start_year: Time.now.year,end_year: (Time.now.year + 10),default: Date.new, date_separator:'%s'),'年','月')+'日' %>&emsp;まで</td>
      </tr>

      <tr>
        <td><%= f.label :その他（注意事項） %></td>
        <td><%= f.text_field :caution %></td>
      </tr>


  </tbody>

  </table>

  <div class = "btn1"><%= f.submit "新規登録", class: "btn btn-primary" %></div>

  <% end %>

  </div>

  </div>

</div>

app/views/admins/construction_sites/show.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

  <div class= "row">

      <div class="col-xs-4">

        <div class="title">現場詳細</div>

        <table class="table">
          <tbody>
            <tr>
              <th>現場名</th>
              <td><%= @construction_site.name %></td>
            </tr>

            <tr>
              <th>現場住所</th>
              <td><%= @construction_site.address %></td>
            </tr>

            <tr>
              <th>元請け業者</th>
              <td><%= @construction_site.prime_contractor %></td>
            </tr>

            <tr>
              <th>現場職長</th>
              <td><%= @construction_site.foremen %></td>
            </tr>

            <tr>
              <th>現在の工程</th>
              <td><%= @construction_site.process %></td>
            </tr>

            <tr>
              <th>工期</th>
              <td><%= @construction_site.period.strftime("%Y-%m-%d") %> 〜<br>
                  <%= @construction_site.period_end.strftime("%Y-%m-%d") %>（予定）</td>
            </tr>

            <tr>
              <th>その他（注意事項）</th>
              <td><%= @construction_site.caution %></td>
            </tr>
          </tbody>
        </table>

        <div class="btn1"><%= link_to "編集する",edit_admins_construction_site_path, class: 'btn btn-primary' %></div>
      </div>

      <div class="col-xs-8">

        <div class="title">現場写真</div>

        <% @photos.each do |photo| %>

        <% if photo.construction_site.id == @construction_site.id %>
        <div class="col-xs-4">
            <div class="img-thumbnail">
              <%= link_to admins_photo_path(photo.id) do %>
                <%= attachment_image_tag photo, :image, :fill, 200, 200 %>
              <% end %>
                <figure class="caption">
                  <%= photo.created_at.strftime('%Y/%m/%d') %>
                </figure>
            </div>
        </div>
        <% end %>

        <% end %>

      </div>

      <div class = "paginate"><%= paginate @photos %></div>

  </div>

</div>