config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  get 'about' => 'abouts#about'

#初期のdeviseの設定だとadminとuserで見分けがつけにくい為下記記述でわかりやすくする
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}





  namespace :admins do
  	resources :users, only:[:index, :show, :edit, :update]
  	resources :construction_sites, only:[:index, :new, :create, :show, :edit, :update]
  	resources :photos, only:[:index, :show]
  	resources :attendance_records, only:[:index, :show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :machines, only:[:index, :create, :update]
    resources :reservations, only:[:index, :new, :create, :show, :destroy]
    resources :cars, only:[:index, :create, :edit, :update]
  	root 'homes#top'
  end




  namespace :users do
  	resources :attendance_records, only:[:index, :create, :show, :edit, :update] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:create, :show, :edit, :update, :destroy] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :users, only:[:show, :edit, :update]
  	resources :construction_sites, only:[:index, :show, :edit, :update] do
      member do
        get :map, as: :map
      end
    end
  	resources :photos, only:[:new, :create, :show, :destroy]
  	resources :machines, only:[:index, :update]
    resources :reservations, only:[:index, :new, :create, :show]
  	root 'homes#top'
  end

  namespace :users do
    get 'uploader/index'
    get 'uploader/download'
  end
  namespace :admins do
    get 'uploader/index'
    post 'uploader/upload'
    get 'uploader/download'
  end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance_record.rb
class AttendanceRecord < ApplicationRecord

	belongs_to :user
	belongs_to :construction_site

	validates :construction_site, presence: true


end

app/models/car.rb
class Car < ApplicationRecord

	has_many :reservations

	validates :name, presence: true

end

app/models/construction_site.rb
class ConstructionSite < ApplicationRecord

	has_many :attendance_records
	has_many :daily_reports
	has_many :machines
  has_many :reservations
  has_many :upload_files
	has_many :photos, dependent: :destroy
  accepts_attachments_for :photos, attachment: :image

  validates :name, presence: true
  validates :address, presence: true
  validates :prime_contractor, presence: true
  validates :foremen, presence: true
  validates :period, presence: true
  validates :period_end, presence: true
  validates :caution, presence: true

	enum process:{
    着工前: 0,
    着工中: 1,
    完工: 2,
    その他: 3,
  }

  def self.search(search)
      if search
        ConstructionSite.where(['name LIKE ? OR address LIKE ? OR prime_contractor LIKE ? OR foremen LIKE ?',
         "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
      else
        ConstructionSite.all
      end
  end


end

app/models/daily_report.rb
class DailyReport < ApplicationRecord

	belongs_to :construction_site

	validates :construction_site, presence: true
	validates :content, presence: true
	validates :company_people, presence: true

end

app/models/machine.rb
class Machine < ApplicationRecord

	belongs_to :construction_site

	validates :name, presence: true

	def self.search(search)
      if search
        Machine.where(['name LIKE ? OR construction_site_id LIKE ?',
         "%#{search}%", "%#{search}%"])
      else
        Machine.all
      end
  end

end

app/models/photo.rb
class Photo < ApplicationRecord

	belongs_to :construction_site

	attachment :image, destroy: false

end

app/models/reservation.rb
class Reservation < ApplicationRecord

	belongs_to :car
	belongs_to :construction_site

	validates :content, presence: true

end

app/models/upload_file.rb
class UploadFile < ApplicationRecord
	mount_uploader :file, UploadFileUploader
	belongs_to :construction_site
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :attendance_records


	validates :family_name, presence: true
  	validates :first_name, presence: true
  	validates :family_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/ }, length: { maximum: 20 }
  	validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}, length: { maximum: 20 }
  	validates :address, presence: true
  	validates :telephone_number, presence: true, numericality: { only_integer: true }
  	validates :email, presence: true

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

	def about
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
		case resource
		when Admin
	    	admins_root_path
	  	when User
	    	users_root_path
	  	end
	end

	def after_sign_up_path_for(resource)
		admins_users_path
	end

	# def after_sign_out_path_for(resource)
	# 	case resource
	# 	when Admin
	# 		new_admin_session_path
	# 	when User
	# 		new_user_session_path
	# 	end
	# end


	# deviseに関わる全てのアクションの前にconfigure_permitted_parametersをさせる
	# つまりキーをコントローラに受け取らせる
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:family_name, :first_name , :family_name_kana, :first_name_kana, :postal_code, :address,:telephone_number])
	end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins/cars_helper.rb
module Admins::CarsHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/shared/_about_header.html.erb
<script src="https://kit.fontawesome.com/ed00617fa7.js" crossorigin="anonymous"></script>

<div class="navbar navbar-fixed-top" role="navigation">

  <div class="sitename_about">
    <div class="container-fluid">
      <div class="parent">
        <h2>GENBA-MASTER</h2>
            <div class="welcome">
              <%= link_to root_path, :style=>"color:white;" do %>
                <i>ログイン画面へ戻る</i>
              <% end %>
            </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">

    <div class="navbar-header">

      <ul class="nav na-tabs nav-justified">

        <% if user_signed_in? %>

          <li>
            <%= link_to users_user_path(current_user.id), :style=>"color:black;" do %>
              <i class="fas fa-user">&ensp;マイページ・天気</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_root_path, :style=>"color:black;" do %>
              <i class="fas fa-clock">&ensp;打刻・日報</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_construction_sites_path, :style=>"color:black;" do %>
              <i class="fas fa-hard-hat">&ensp;現場一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_machines_path, :style=>"color:black;" do %>
              <i class="fas fa-tools">&ensp;機械・機材一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_reservations_path, :style=>"color:black;" do %>
              <i class="fas fa-truck-loading">&ensp;配車予約カレンダー</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_uploader_index_path, :style=>"color:black;" do %>
              <i class="fas fa-file-pdf">&ensp;PDF書類</i>
            <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, :style=>"color:black;", method: :delete do %>
              <i class="fas fa-sign-out-alt">&ensp;ログアウト</i>
            <% end %>
          </li>

        <% end %>

      </ul>

    </div>

  </div>

</div>

<footer class="navbar navbar-fixed-bottom", style="background-color: #7d7d7d;"></footer>

app/views/shared/_admin_header.html.erb
<script src="https://kit.fontawesome.com/ed00617fa7.js" crossorigin="anonymous"></script>

<div class="navbar navbar-fixed-top" role="navigation">

<div class="sitename_admin">
  <div class="container-fluid">
    <div class="parent">
      <h2>&emsp;&emsp;<%= link_to admins_root_path, :style=>"color:white;" do %>GENBA-MASTER<% end %></h2>
        <% if admin_signed_in? %>
        <% else %>
          <div class="welcome">
            <%= link_to new_user_session_path, :style=>"color:white;" do %>
            <i class="fas fa-user">従業員の方はこちら</i>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

    <div class="container-fluid">
      <div class="navbar-header">
        <ul class="nav na-tabs nav-justified">

          <% if admin_signed_in? %>

          <li>
            <%= link_to admins_users_path, :style=>"color:black;" do %>
            <i class="fas fa-user">&ensp;従業員一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to admins_construction_sites_path, :style=>"color:black;" do %>
            <i class="fas fa-hard-hat">&ensp;現場一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to admins_machines_path, :style=>"color:black;" do %>
            <i class="fas fa-tools">&ensp;機械・機材一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to admins_cars_path, :style=>"color:black;" do %>
            <i class="fas fa-truck">&ensp;車両一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to admins_reservations_path, :style=>"color:black;" do %>
            <i class="fas fa-truck-loading">&ensp;配車予約カレンダー</i>
            <% end %>
          </li>

          <li>
            <%= link_to admins_uploader_index_path, :style=>"color:black;" do %>
            <i class="fas fa-file-pdf">&ensp;PDF共有</i>
            <% end %>
          </li>

          <li>
            <%= link_to destroy_admin_session_path, class: 'up', method: :delete, :style=>"color:black;" do %>
            <i class="fas fa-sign-out-alt">&ensp;ログアウト</i>
            <% end %>
          </li>

          <% end %>

        </ul>
      </div>
    </div>
  </div>





<footer class="navbar navbar-fixed-bottom", style="background-color: #000000;"></footer>

app/views/shared/_user_header.html.erb
<script src="https://kit.fontawesome.com/ed00617fa7.js" crossorigin="anonymous"></script>

<div class="navbar navbar-fixed-top" role="navigation">

<div class="sitename_user">
  <div class="container-fluid">
    <div class="parent">
      <h2>GENBA-MASTER</h2>
        <% if user_signed_in? %>
          <div class="welcome"><%= current_user.family_name %>さん！ 本日もおつかれさまです！</div>
        <% else %>
          <div class="welcome">
            <%= link_to new_admin_session_path, :style=>"color:white;" do %>
            <i class="fas fa-user">管理者の方はこちら</i>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

    <div class="container-fluid">
      <div class="navbar-header">

        <ul class="nav na-tabs nav-justified">

          <% if user_signed_in? %>

          <li>
            <%= link_to users_user_path(current_user.id), :style=>"color:black;" do %>
            <i class="fas fa-user">&ensp;マイページ・天気</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_root_path, :style=>"color:black;" do %>
            <i class="fas fa-clock">&ensp;打刻・日報</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_construction_sites_path, :style=>"color:black;" do %>
            <i class="fas fa-hard-hat">&ensp;現場一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_machines_path, :style=>"color:black;" do %>
            <i class="fas fa-tools">&ensp;機械・機材一覧</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_reservations_path, :style=>"color:black;" do %>
            <i class="fas fa-truck-loading">&ensp;配車予約カレンダー</i>
            <% end %>
          </li>

          <li>
            <%= link_to users_uploader_index_path, :style=>"color:black;" do %>
            <i class="fas fa-file-pdf">&ensp;PDF書類</i>
            <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, :style=>"color:black;", method: :delete do %>
            <i class="fas fa-sign-out-alt">&ensp;ログアウト</i>
            <% end %>
          </li>

          <% end %>

        </ul>

      </nav>

    </div>
  </div>
</div>





<footer class="navbar navbar-fixed-bottom", style="background-color: #006699;"></footer>