config/routes.rb
Rails.application.routes.draw do

  root 'users/homes#top'
  get 'about' => 'abouts#about'

#初期のdeviseの設定だとadminとuserで見分けがつけにくい為下記記述でわかりやすくする
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}





  namespace :admins do
  	resources :users, only:[:index, :show, :edit, :update]
  	resources :construction_sites, only:[:index, :new, :create, :show, :edit, :update]
  	resources :photos, only:[:index, :show]
  	resources :attendance_records, only:[:index, :show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:show] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :machines, only:[:index, :create, :update]
    resources :reservations, only:[:index, :new, :create, :show, :destroy]
    resources :cars, only:[:index, :create, :edit, :update]
  	root 'homes#top'
  end




  namespace :users do
  	resources :attendance_records, only:[:index, :create, :show, :edit, :update] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :daily_reports, only:[:create, :show, :edit, :update, :destroy] do
      member do
        get :calendar, as: :calendar
      end
    end
  	resources :users, only:[:show, :edit, :update]
  	resources :construction_sites, only:[:index, :show, :edit, :update] do
      member do
        get :map, as: :map
      end
    end
  	resources :photos, only:[:new, :create, :show, :destroy]
  	resources :machines, only:[:index, :update]
    resources :reservations, only:[:index, :new, :create, :show]
  	root 'homes#top'
  end

  namespace :users do
    get 'uploader/index'
    get 'uploader/download'
  end
  namespace :admins do
    get 'uploader/index'
    post 'uploader/upload'
    get 'uploader/download'
  end





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :attendance_records


	validates :family_name, presence: true
  	validates :first_name, presence: true
  	validates :family_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/ }, length: { maximum: 20 }
  	validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}, length: { maximum: 20 }
  	validates :address, presence: true
  	validates :telephone_number, presence: true, numericality: { only_integer: true }
  	validates :email, presence: true

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
 before_action :authenticate_admin!
 GET_LIMIT = 10

	def index
    	@users = User.all.page(params[:page]).per(GET_LIMIT)
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
    	if @user.update(user_params)
          flash[:notice] = "従業員情報を変更しました！"
      		redirect_to admins_user_path(@user.id)
    	else
      		render action: :edit
    	end
	end


	private
  		def user_params
    		params.require(:user).permit(
      			:family_name,
      			:first_name,
      			:family_name_kana,
      			:first_name_kana,
      			:email,
      			:address,
      			:telephone_number,
      			:is_withdrawal)
  		end

end

app/controllers/users/attendance_records_controller.rb
class Users::AttendanceRecordsController < ApplicationController
 before_action :authenticate_user!

	def create
		@attendance_record = AttendanceRecord.new(attendance_record_params)
		@attendance_record.user_id = current_user.id
		if @attendance_record.save
			flash[:notice] = "打刻しました！"
			redirect_to users_attendance_record_path(@attendance_record.id)
		else
			@attendance_record = AttendanceRecord.new
			@daily_report = DailyReport.new
			flash[:danger] = '打刻/日報作成に失敗しました。再度入力をお願いします。'
			render template: 'users/homes/top'
		end
	end

	def calendar
		@attendance_records = AttendanceRecord.where(user_id: params[:id])
	end

	def show
		@attendance_record = AttendanceRecord.find(params[:id])
	end

	def edit
		@attendance_record = AttendanceRecord.find(params[:id])
	end

	def update
		@attendance_record = AttendanceRecord.find(params[:id])
		if @attendance_record.update(attendance_record_params)
			flash[:notice] = "打刻内容を変更しました！"
			redirect_to users_attendance_record_path(@attendance_record.id)
		else
			render action: :edit
		end
	end

	private
  		def attendance_record_params
    		params.require(:attendance_record).permit(
    			:user_id,
   				:construction_site_id,
   				:start_time,
   				:finish_at)
  		end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/construction_sites_controller.rb
class Users::ConstructionSitesController < ApplicationController
 before_action :authenticate_user!
 GET_LIMIT = 10

	def index
		@construction_sites = ConstructionSite.page(params[:page]).per(GET_LIMIT).search(params[:search]).order(created_at: :desc)
	end

	def show
		@construction_site = ConstructionSite.find(params[:id])
		@photos = @construction_site.photos.page(params[:page]).per(6).order(created_at: :desc)
	end

	def map
		@construction_site = ConstructionSite.find(params[:id])
	end

	def edit
		@construction_site = ConstructionSite.find(params[:id])
	end

	def update
		@construction_site = ConstructionSite.find(params[:id])
    	if @construction_site.update(construction_site_params)
    		flash[:notice] = "現場情報を編集しました！"
      		redirect_to users_construction_site_path(@construction_site.id)
    	else
      		render action: :edit
    	end
	end

	private
	def construction_site_params
		params.require(:construction_site).permit(
			:name, :address, :prime_contractor, :foremen, :process, :period, :period_end, :caution)
	end


end

app/controllers/users/daily_reports_controller.rb
class Users::DailyReportsController < ApplicationController
 before_action :authenticate_user!

	def calendar
		@construction_site = ConstructionSite.find(params[:id])
		@daily_reports = DailyReport.where(construction_site_id: params[:id])
	end

	def create
		@daily_report = DailyReport.new(daily_report_params)
		if @daily_report.save
			flash[:notice] = "日報を作成しました！"
			redirect_to users_daily_report_path(@daily_report.id)
		else
			@attendance_record = AttendanceRecord.new
			@daily_report = DailyReport.new
			flash[:danger] = '打刻/日報作成に失敗しました。再度入力をお願いします。'
			render template: 'users/homes/top'
		end
	end

	def show
		@daily_report = DailyReport.find(params[:id])
	end

	def edit
		@daily_report = DailyReport.find(params[:id])
		@construction_sites = ConstructionSite.all
	end

	def update
		@daily_report = DailyReport.find(params[:id])
		if @daily_report.update(daily_report_params)
			flash[:notice] = "日報を編集しました！"
			redirect_to users_daily_report_path(@daily_report.id)
		else
			render action: :edit
		end
	end

	def destroy
		@daily_report = DailyReport.find(params[:id])
		if @daily_report.destroy
			flash[:notice] = "日報を削除しました！！"
			redirect_to calendar_users_daily_report_path(@daily_report.id)
		else
			render :show
		end
	end

	private
  		def daily_report_params
    		params.require(:daily_report).permit(
    			:construction_site_id,
    			:date,
    			:content,
    			:etcetera,
    			:company_people,
    			:care_people,
    			:scaffold_people,
    			:interior_people,
    			:welder,
    			:watchman,
    			:garbage_collection_car,
    			:big_garbage_collection_car,
    			:concrete_car,
    			:big_concrete_car,
    			:soil_car,
    			:start_time,
    			:etcetera_people)
  		end


end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
 before_action :authenticate_user!

	def top
		@attendance_record = AttendanceRecord.new
		@daily_report = DailyReport.new
		wd = ["日", "月", "火", "水", "木", "金", "土"]
		time = Time.new
		@date = time.strftime("%Y年 %m月 %d日(#{wd[time.wday]})")
	end


end

app/controllers/users/machines_controller.rb
class Users::MachinesController < ApplicationController
 before_action :authenticate_user!

	def index
		@machines = Machine.all.page(params[:page]).per(7).search(params[:search]).order(created_at: :desc)
	end

	def update
		@machine = Machine.find(params[:id])
    	if @machine.update(machine_params)
    		flash[:notice] = "機械・機材情報を編集しました！"
      		redirect_to	users_machines_path
    	else
      		redirect_to users_root_path
    	end
	end

	private
	def machine_params
		params.require(:machine).permit(
			:construction_site_id, :name, :need_repair)
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
 before_action :authenticate_user!

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)
		if @photo.save
			flash[:notice] = "現場写真を投稿しました！"
			redirect_to users_construction_site_path(@photo.construction_site_id)
		else
			render :new
		end
	end

	def show
		@photo = Photo.find(params[:id])
	end

	def destroy
		@photo = Photo.find(params[:id])
		if @photo.destroy
			flash[:notice] = "現場写真を削除しました！！"
			redirect_to users_construction_sites_path
		else
			render :show
		end
	end

	private
  		def photo_params
    		params.require(:photo).permit(
    			:construction_site_id,:image,:explanation)
  		end


end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
 prepend_before_action :require_no_authentication, only: [:cancel]
  before_action :authenticate_admin!
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
     admins_users_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
     after_sign_in_path_for(resource)
  end
end

app/controllers/users/reservations_controller.rb
class Users::ReservationsController < ApplicationController
 before_action :authenticate_user!

	def index
		@reservations = Reservation.all
	end

	def new
		@reservation = Reservation.new
	end

	def create
		@reservation = Reservation.new(reservation_params)
		if @reservation.save
			flash[:notice] = "配車予約が完了しました！"
			redirect_to users_reservations_path
		else
			render action: :new
		end
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	private
  		def reservation_params
    		params.require(:reservation).permit(
    			:car_id,
   				:construction_site_id,
   				:content,
   				:start_time,
   				:finish_at)
  		end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    # respond_to_on_destro
    redirect_to new_user_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/uploader_controller.rb
class Users::UploaderController < ApplicationController
  def index
  	@uploads = UploadFile.all.reverse_order
  end

  def download
    @upload_file = UploadFile.find(params[:id].to_i)
    filepath = @upload_file.file.current_path
    stat = File::stat(filepath)
    send_file(filepath, :filename => @upload_file.file.url.gsub(/.*\//,''), :length => stat.size)
  end


end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
 before_action :authenticate_user!

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "情報を変更しました！"
      redirect_to users_user_path(current_user.id)
    else
      render :edit
    end
  end



	private
  def user_params
    	params.require(:user).permit(
        :family_name,
      	:first_name,
      	:family_name_kana,
      	:first_name_kana,
      	:email,
      	:address,
      	:telephone_number,
      	:is_withdrawal,
        :wheather_prefecture)
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users/attendance_records_helper.rb
module Users::AttendanceRecordsHelper
end

app/views/admins/users/edit.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

  <div class= "row">

    <div class="col-xs-7">

    <div class="title">
	 		<%= @user.family_name %>
      <%= @user.first_name %>さんの情報編集
		</div>

			<%= form_for @user, url: admins_user_path do |f| %>

    		<table border="0">
      			<tr>
        			<th>会員ID</th>
        			<td>
          			<%= @user.id %>
       				</td>
      			</tr>


      			<tr>
        			<th>氏名</th>
        			<td><%= f.text_field :family_name, class: "form-control" %></td>
       				<td>&nbsp;&nbsp;&nbsp;</td>
        			<td><%= f.text_field :first_name, class: "form-control" %></td>
      			</tr>

      			<tr>
        			<th>フリガナ</th>
        			<td><%= f.text_field :family_name_kana, class: "form-control" %></td>
        			<td>&nbsp;&nbsp;&nbsp;</td>
        			<td><%= f.text_field :first_name_kana, class: "form-control" %></td>
      			</tr>

      			<tr>
        			<th>住所</th>
        			<td colspan="3">
          			<%= f.text_field :address, class: "form-control" %>
        			</td>
      			</tr>

      			<tr>
        			<th>電話番号</th>
        			<td>
          			<%= f.text_field :telephone_number, class: "form-control" %>
        			</td>
      			</tr>

      			<tr>
        			<th>メールアドレス</th>
        			<td>
          			<%= f.text_field :email, class: "form-control" %>
        			</td>
      			</tr>

      			<tr>
        			<th>会員ステータス</th>
        			<td>
          			<label>
            			<%= f.radio_button :is_withdrawal, :false %>有効
          			</label>
          			<label>
            			<%= f.radio_button :is_withdrawal, :true %>退会済み
          			</label>
       				</td>
      			</tr>
    		</table>

    		<%= f.submit('変更を保存',class: 'btn btn-primary', style: 'margin: 10px 0px 20px 0px') %>
    		<% end %>

    	</div>
    </div>
</div>

app/views/admins/users/index.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

	<div class= "row">

  		<div class="col-xs-11">

    		<div class="title">従業員一覧&ensp;
	 				<%= link_to new_user_registration_path, :style=>"color:black;" do %>
	 					<i class="fas fa-user-plus"></i>
	 				<% end %>
			</div>

	<table style="margin-top:15px">

	    <thead class = "thead-light">
	      <tr class="active">
		    <th style="width:15%">従業員ID</th>
		    <th style="width:25%">氏名</th>
		    <th style="width:30%">メールアドレス</th>
		    <th style="width:10%">ステータス</th>
		    <th style="width:20%">&emsp;</th>
		  </tr>
	    </thead>

	  <% @users.each do |user| %>
	    <tbody>
		  <tr>
		    <td><%= user.id %></td>
			<td>
				<%= link_to admins_user_path(user.id) do %>
					<%= "#{user.family_name}#{user.first_name}" %>
				<% end %>
			</td>
			<td><%= user.email %></td>
			<td>
	          <% if user.is_withdrawal == false %>
		        <p>有効</p>
		      <% else %>
		        <p>退会済</p>
		      <% end %>
			</td>
			<td> &emsp; <%= link_to "出勤簿",calendar_admins_attendance_record_path(user.id), class: 'btn btn-primary' %></td>
		  </tr>
		</tbody>
	  <% end %>
	</table>

	<div class = "paginate"><%= paginate @users %></div>

  </div>
</div>

app/views/admins/users/show.html.erb
<%= render "shared/admin_header" %>

<div class = "container">

	<div class= "row">

    <div class="col-xs-7">

    <div class="title">
      <%= @user.family_name %>
      <%= @user.first_name %>さんの情報詳細
    </div>

			<table class = "table table-bordered">
      			<tr>
        			<th>従業員ID</th>
        			<td>
          				<%= @user.id %>
        			</td>
      			</tr>

      			<tr>
        			<th>氏名</th>
        			<td>
          				<%= @user.family_name %>
          				<%= @user.first_name %>
        			</td>
      			</tr>

      			<tr>
        			<th>フリガナ</th>
        			<td>
          				<%= @user.family_name_kana %>
          				<%= @user.first_name_kana %>
        			</td>
      			</tr>

     			  <tr>
        		  <th>住所</th>
              <td><%= @user.address %></td>
      			</tr>

      			<tr>
        			<th>電話番号</th>
        			<td><%= @user.telephone_number %></td>
      			</tr>

      			<tr>
        			<th>メールアドレス</th>
        			<td><%= @user.email %></td>
     			  </tr>

     			  <tr>
     			    <th>ステータス</th>
     			    <td><% if @user.is_withdrawal == false %>
              				<span class="status">有効会員</span>
            			<% else %>
              				<span class="status">退会済会員</span>
            			<% end %>
            	</td>
            </tr>

    		</table>

    		<div class = "btn1">
      			<%=link_to "編集する", edit_admins_user_path(@user.id),class: "btn btn-primary", style:"margin-right:30px" %>
    		</div>

    	</div>
    </div>
</div>